export const SET_ENTITY = "SET_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";

export const SET_PIZZA = "SET_PIZZA";
export const SET_DOUGH = "SET_DOUGH";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_SAUCES = "SET_SAUCES";
export const SET_SIZES = "SET_SIZES";
export const SET_FORM_DOUGH = "SET_FORM_DOUGH";
export const ADD_FORM_INGREDIENTS = "ADD_FORM_INGREDIENTS";
export const UPDATE_COUNT_FORM_INGREDIENTS = "UPDATE_COUNT_FORM_INGREDIENTS";
export const SET_FORM_INGREDIENTS = "SET_FORM_INGREDIENTS";
export const SET_FORM_SAUCES = "SET_FORM_SAUCES";
export const SET_FORM_SIZES = "SET_FORM_SIZES";
export const SET_INGREDIENTS_PRICE = "SET_INGREDIENTS_PRICE";
export const SET_FORM_PIZZA_NAME = "SET_FORM_PIZZA_NAME";
